CREATE TABLE IF NOT EXISTS T_WORKING_SCHEDULE (
    ID_WORKING_SCHEDULE SERIAL PRIMARY KEY,
    ID_LAWYER INTEGER NOT NULL, -- Relación 1:N (Un abogado, muchos rangos horarios)
    DAY_OF_WEEK VARCHAR(10) NOT NULL, -- Ej: 'Monday', 'Tuesday'
    START_TIME TIME NOT NULL,
    END_TIME TIME NOT NULL
);

CREATE TABLE IF NOT EXISTS T_CLIENTS (
    ID_CLIENT SERIAL PRIMARY KEY,
    COMPANY_ID VARCHAR(50) NOT NULL,
    TRADE_NAME VARCHAR(255) NOT NULL,
    LOCATION VARCHAR(255) NOT NULL,
    TIMEZONE VARCHAR(50) NOT NULL DEFAULT 'UTC'
);

CREATE TABLE IF NOT EXISTS T_LAWYERS (
    ID_LAWYER SERIAL PRIMARY KEY,
    NATIONAL_ID VARCHAR(50) NOT NULL UNIQUE,
    FULL_NAME VARCHAR(255) NOT NULL,
    LOCATION VARCHAR(255) NOT NULL,
    TIMEZONE VARCHAR(50) NOT NULL DEFAULT 'UTC'
);

CREATE TABLE IF NOT EXISTS T_VACATIONS (
    ID_VACATION SERIAL PRIMARY KEY,
    ID_LAWYER INTEGER NOT NULL REFERENCES T_LAWYERS(ID_LAWYER) ON DELETE CASCADE,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    CONSTRAINT CHK_VACATION_DATES CHECK (END_DATE >= START_DATE)
);

CREATE TABLE IF NOT EXISTS T_CONTACT (
    ID_CONTACT SERIAL PRIMARY KEY,
    ID_LAWYER INTEGER REFERENCES T_LAWYERS(ID_LAWYER) ON DELETE CASCADE,
    ID_CLIENT INTEGER REFERENCES T_CLIENTS(ID_CLIENT) ON DELETE CASCADE,
    METHOD_TYPE VARCHAR(20) NOT NULL, -- 'InPerson', 'VideoCall', 'PhoneCall'
    VALUE VARCHAR(255) NOT NULL,
    IS_DEFAULT BOOLEAN NOT NULL DEFAULT FALSE,
    
    CONSTRAINT CHK_SINGLE_ENTITY CHECK (
        (ID_LAWYER IS NOT NULL AND ID_CLIENT IS NULL) OR 
        (ID_LAWYER IS NULL AND ID_CLIENT IS NOT NULL)
    ),
    CONSTRAINT CHK_METHOD_TYPE CHECK (METHOD_TYPE IN ('InPerson', 'VideoCall', 'PhoneCall'))
);

CREATE TABLE IF NOT EXISTS T_APPOINTMENTS (
    ID_APPOINTMENT SERIAL PRIMARY KEY,
    SUBJECT VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    START_DATETIME TIMESTAMPTZ NOT NULL,
    END_DATETIME TIMESTAMPTZ NOT NULL,
    ID_LAWYER INTEGER NOT NULL REFERENCES T_LAWYERS(ID_LAWYER),
    ID_CLIENT INTEGER NOT NULL REFERENCES T_CLIENTS(ID_CLIENT),
    ID_SELECTED_CONTACT INTEGER NOT NULL REFERENCES T_CONTACT(ID_CONTACT),
    
    CONSTRAINT CHK_APPOINTMENT_TIME CHECK (END_DATETIME > START_DATETIME)
);

---
--- Índices y Relaciones Adicionales
---

-- FK para Working Schedule (que no pudimos poner en el CREATE TABLE por orden de ejecución)
ALTER TABLE T_WORKING_SCHEDULE 
ADD CONSTRAINT FK_SCHEDULE_LAWYER 
FOREIGN KEY (ID_LAWYER) REFERENCES T_LAWYERS(ID_LAWYER) ON DELETE CASCADE;

-- Índices para mejorar rendimiento en JOINs y búsquedas frecuentes
CREATE INDEX IDX_SCHEDULE_LAWYER ON T_WORKING_SCHEDULE(ID_LAWYER);
CREATE INDEX IDX_VACATIONS_LAWYER ON T_VACATIONS(ID_LAWYER);
CREATE INDEX IDX_CONTACT_LAWYER ON T_CONTACT(ID_LAWYER) WHERE ID_LAWYER IS NOT NULL;
CREATE INDEX IDX_CONTACT_CLIENT ON T_CONTACT(ID_CLIENT) WHERE ID_CLIENT IS NOT NULL;
CREATE INDEX IDX_APPOINTMENTS_LAWYER_DATE ON T_APPOINTMENTS(ID_LAWYER, START_DATETIME);
CREATE INDEX IDX_APPOINTMENTS_CLIENT_DATE ON T_APPOINTMENTS(ID_CLIENT, START_DATETIME);